# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: TetherToken
    address:
    - 0xdAC17F958D2ee523a2206206994597C13D831ec7
    - 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
    - 0x6B175474E89094C44Da98b954EedeAC495271d0F
    - 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
    - 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9
    - 0xc00e94Cb662C3520282E6f5717214004A7f26888
    - 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
    - 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
    - 0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2
    - 0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e
    - 0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0
    - 0x514910771AF9Ca656af840dff83E8264EcF986CA
    handler: src/EventHandlers.ts
    events:
    - event: AddedBlackList(address _user)
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Deprecate(address newAddress)
    - event: DestroyedBlackFunds(address _blackListedUser, uint256 _balance)
    - event: Issue(uint256 amount)
    - event: Params(uint256 feeBasisPoints, uint256 maxFee)
    - event: Pause()
    - event: Redeem(uint256 amount)
    - event: RemovedBlackList(address _user)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: Unpause()
rollback_on_reorg: false
